---
title: "scales_y_coordinates"
output:
   html_document:
      toc: TRUE
      toc_float: TRUE
      fig_width: 10.5
      theme: 'journal'
      code_folding: 'hide'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lectura

Importamos los datos
```{r cars}
library(tidyverse)
diamantes <- diamonds %>% 
    mutate(across(c(cut, color, clarity), ~ parse_factor(as.character(.x))))
```

## Scales
```{r pressure, echo=FALSE}

diamantes %>% 
    ggplot() +
    geom_point(aes(y = price, x = carat, color = cut)) +
    scale_x_continuous(breaks = c(1, 2, 3), 
                        labels = c('Fox', 'Calder칩n', 'Pe침a')) # +
    # ggsave('figs/viz1.png', height = 5.5, width = 7.5)


diamantes %>% 
    ggplot() +
    geom_point(aes(y = price, x = carat, color = cut)) +
    scale_x_continuous(breaks = c(1, 2, 3), 
                       labels = c('Fox', 'Calder칩n', 'Pe침a')) +
    scale_y_continuous(breaks = seq(0, 20e3, 2.5e3), 
                       labels = scales::dollar_format(accuracy = 1))

diamantes %>% 
    ggplot() +
    geom_bar(aes(x = cut, fill = color), 
             position = 'fill', 
             alpha = 0.7, 
             color = 'black') +
    geom_hline(yintercept = 0.6, 
               linetype = 'dashed', 
               color = 'red', 
               alpha = 0.5, 
               size = 2) +
    scale_y_continuous(breaks = seq(0, 1, by = 0.1), 
                       labels = scales::percent_format(accuracy = 1)) +
    scale_fill_manual(values = c('red', 'yellow', 'blue', 'purple', 'brown', 'orange', 'green')) +
    theme_classic() 
```

## Coordinates
```{r}
diamantes %>% 
    ggplot() +
    geom_bar(aes(x = cut, fill = color), 
             position = 'fill', 
             alpha = 0.7, 
             color = 'black') +
    geom_hline(yintercept = 0.6, 
               linetype = 'dashed', 
               color = 'red', 
               alpha = 0.5, 
               size = 2) +
    scale_y_continuous(breaks = seq(0, 1, by = 0.1), 
                       labels = scales::percent_format(accuracy = 1)) +
    scale_fill_manual(values = c('red', 'yellow', 'blue', 'purple', 'brown', 'orange', 'green')) +
    theme_classic() +
    coord_polar()

diamantes %>% 
    ggplot() +
    geom_bar(aes(x = cut, fill = color), 
             position = 'fill', 
             alpha = 0.7, 
             color = 'black') +
    geom_hline(yintercept = 0.6, 
               linetype = 'dashed', 
               color = 'red', 
               alpha = 0.5, 
               size = 2) +
    scale_y_continuous(breaks = seq(0, 1, by = 0.1), 
                       labels = scales::percent_format(accuracy = 1)) +
    scale_fill_manual(values = c('red', 'yellow', 'blue', 'purple', 'brown', 'orange', 'green')) +
    theme_classic() +
    coord_flip()
```



